const Productdata = [
  {
    id: 1,
    image: "/images/img1.webp",
    secondaryImage: "/images/img-1.webp",
    smallimage: "/smalimages/s1.webp",
    itemSize: "XL | Tony Hawk",
    itemQty: 1,
    productDesc: "Cropped Stay Groovy ",
    currncey: "$",
    price: "16.90",
    text: "or 9x",
    sale: "$1.21",
    size: ["X", "L", "Xl", "XXL"],
  },
  {
    id: 2,
    image: "/images/img2.webp",
    secondaryImage: "/images/img-2.webp",
    smallimage: "/smalimages/s2.webp",
    itemSize: "XL | Tony Hawk",
    productDesc: "Basic Cactus White T-shirt",
    currncey: "$",
    price: "10.00",
    text: "or 9x",
    sale: "$1.21",
    itemQty: 1,
    size: ["XL", "XXL", "L", "L"],
  },
  {
    id: 3,
    image: "/images/img3.webp",
    secondaryImage: "/images/img-3.webp",
    smallimage: "/smalimages/s3.webp",
    itemSize: "XL | Tony Hawk",
    productDesc: "Skater Black Sweatshirt",
    currncey: "$",
    price: "19.80",
    text: "or 9x",
    sale: "$1.21",
    itemQty: 1,
    size: ["X", "L", "XXL", "M"],
  },
  {
    id: 4,
    image: "/images/img4.webp",
    secondaryImage: "/images/img-4.webp",
    smallimage: "/smalimages/s4.webp",
    itemSize: "XL | Tony Hawk",
    productDesc: "Black Tule Oversized",
    currncey: "$",
    price: "8.40",
    text: "or 9x",
    sale: "$1.21",
    itemQty: 1,
    size: ["X", "L", "XL", "XXL"],
  },
  {
    id: 5,
    image: "/images/img5.webp",
    secondaryImage: "/images/img-5.webp",
    smallimage: "/smalimages/s5.webp",
    itemSize: "XL | Tony Hawk",
    productDesc: "Black Batman T-shirt",
    currncey: "$",
    price: "20.00",
    text: "or 9x",
    sale: "$1.21",
    itemQty: 1,
    size: ["XL", "XXL", "Xs", "L"],
  },
  {
    id: 6,
    image: "/images/img6.webp",
    secondaryImage: "/images/img-6.webp",
    smallimage: "/smalimages/s6.webp",
    itemSize: "XL | Tony Hawk",
    productDesc: "Loose Black T-shirt",
    currncey: "$",
    price: "11.60",
    text: "or 9x",
    sale: "$1.21",
    itemQty: 1,
    size: ["XXL", "Xs ", "XL", "M"],
  },
  {
    id: 7,
    image: "/images/img7.webp",
    productDesc: "Ringer Hall Pass",
    secondaryImage: "/images/img-7.webp",
    smallimage: "/smalimages/s7.webp",
    itemSize: "XL | Tony Hawk",
    currncey: "$",
    price: "18.10",
    text: "or 9x",
    sale: "$1.21",
    itemQty: 1,
    size: ["X", "XXL", "Xs"],
  },
  {
    id: 8,
    image: "/images/img8.webp",
    secondaryImage: "/images/img-8.webp",
    smallimage: "/smalimages/s8.webp",
    itemSize: "XL | Tony Hawk",
    productDesc: "Cropped Stay Groovy off white",
    currncey: "$",
    price: "14.10",
    text: "or 9x",
    sale: "$1.21",
    itemQty: 1,
    size: ["X", "XL", "XXL"],
  },
  {
    id: 9,
    image: "/images/img9.webp",
    secondaryImage: "/images/img-9.webp",
    smallimage: "/smalimages/s9.webp",
    itemSize: "XL | Tony Hawk",
    productDesc: "Cropped Stay Groovy off white",
    currncey: "$",
    price: "9.90",
    text: "or 9x",
    sale: "$1.21",
    itemQty: 1,
    size: ["XL", "XXL", "S"],
  },
  {
    id: 10,
    image: "/images/img10.webp",
    secondaryImage: "/images/img-10.webp",
    smallimage: "/smalimages/s10.webp",
    itemSize: "XL | Tony Hawk",
    productDesc: "Cropped Stay Groovy off white",
    currncey: "$",
    price: "12.00",
    text: "or 9x",
    sale: "$1.21",
    itemQty: 1,
    size: ["L", "XL", "XXL", "S", "Ml"],
  },
  {
    id: 11,
    image: "/images/img11.webp",
    secondaryImage: "/images/img-11.webp",
    smallimage: "/smalimages/s11.webp",
    itemSize: "XL | Tony Hawk",
    productDesc: "Cropped Stay Groovy off white",
    currncey: "$",
    price: "17.30",
    text: "or 9x",
    sale: "$1.21",
    itemQty: 1,
    size: ["X", "XXL", "S", "Xs", "Ml"],
  },
  {
    id: 12,
    image: "/images/img12.webp",
    secondaryImage: "/images/img-12.webp",
    smallimage: "/smalimages/s12.webp",
    itemSize: "XL | Tony Hawk",
    productDesc: "Cropped Stay Groovy off white",
    currncey: "$",
    price: "11.10",
    text: "or 9x",
    sale: "$1.21",
    itemQty: 1,
    size: ["X", "L", "XL", "S", "M"],
  },
];
export default Productdata;
